using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class SelectionManager : MonoBehaviour
{
    [SerializeField] private Material highlightMaterial;

    // Update is called once per frame
    void Update()
    {
        //var ray = Camera.main.ScreenPointToRay(Input.mousePosition);
        //Point
        //RaycastHit hit;
        //if(Physics.Raycast(ray, out hit))
        //{
        //    var seleciton = hit.transform;
        //    var selectionRenderer = seleciton.GetComponent<Renderer>();
        //    if(selectionRenderer != null)
        //    {
        //        selectionRenderer.material = highlightMaterial;
        //    }
        //}
    }
}
